version: '3.4'

services:
    sqldb:
        image: mcr.microsoft.com/mssql/server

    catalogdb:
        image: mongo

    basketdb:
        image: redis

    rabbitmq:
        image: rabbitmq:3-management-alpine

    identity.api:
        image: ${DOCKER_REGISTRY-}identityapi
        build:
            context: .
            dockerfile: src/Identity/Identity.API/Dockerfile

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: src/Catalog/Catalog.API/Dockerfile

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: src/Basket/Basket.API/Dockerfile

    checkout.api:
        image: ${DOCKER_REGISTRY-}checkoutapi
        build:
            context: .
            dockerfile: src/Checkout/Checkout.API/Dockerfile

    apigw:
        image: ${DOCKER_REGISTRY-}apigw
        build:
            context: .
            dockerfile: src/ApiGateway/ApiGw/Dockerfile
