version: '3.4'

services:
    authdb:
        container_name: authdb
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"

    catalogdb:
        container_name: catalogdb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db 
        ports:
            - "27017:27017"

    identity.api:
        container_name: identityapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "SqlServer:ConnectionString=Server=authdb;Database=AuthDb;User Id=sa;Password=yourStrong(!)Password"
        depends_on:
            - authdb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8000:80"

    catalog.api:
        container_name: catalogapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "MongoDb:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8001:80"
